name: validate org

on:
  pull_request:
    branches:
      - main
    paths:
      - 'force-app/**'
jobs:
  validate:
    runs-on: ubuntu-latest
    setps:
      - uses: actions/checkout@v3
      - name: Validate On org
        uses: jawills/sf-deploy@v1.0
        with: 
          SFDX_AUTH_URL: ${{secrets.SFDX_AUTH_URL}}
          DRY_RUN: true